/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Arboles.Arbol;
import Generar.Generar_numeros;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Arbol arbol = new Arbol();
    Generar_numeros recorridos = new Generar_numeros();
        
        
    public frm_Menu() throws IOException {
        initComponents();
        arbol = recorridos.Generar();
        System.out.println("Numeros Generados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_InOrden = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_PosOrden = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_PreOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("RECORRIDO DE ARBOLES BINARIOS");

        jLabel2.setText("HACER RECORRIDO INORDEN");

        btn_InOrden.setBackground(new java.awt.Color(51, 51, 51));
        btn_InOrden.setForeground(new java.awt.Color(255, 255, 0));
        btn_InOrden.setText("GENERAR");
        btn_InOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InOrdenActionPerformed(evt);
            }
        });

        jLabel3.setText("HACER RECORRIDO POSTORDEN");

        btn_PosOrden.setBackground(new java.awt.Color(51, 51, 51));
        btn_PosOrden.setForeground(new java.awt.Color(255, 255, 0));
        btn_PosOrden.setText("GENERAR");
        btn_PosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PosOrdenActionPerformed(evt);
            }
        });

        jLabel4.setText("HACER RECORRIDO PREORDEN");

        btn_PreOrden.setBackground(new java.awt.Color(51, 51, 51));
        btn_PreOrden.setForeground(new java.awt.Color(255, 255, 0));
        btn_PreOrden.setText("GENERAR");
        btn_PreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_InOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(btn_PosOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PreOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_InOrden)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btn_PosOrden)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btn_PreOrden)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.InOrden();
            System.out.println("InOrden generado correctamente");
            System.out.println("InOrden generado correctamente");
        } catch (IOException ex) {
            Logger.getLogger(frm_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_InOrdenActionPerformed

    private void btn_PosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PosOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.PosOrden();
            System.out.println("PosOrden Generado Correctamente");
            System.out.println("PosOrden Generado Correctamente");
        } catch (IOException ex) {
            Logger.getLogger(frm_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PosOrdenActionPerformed

    private void btn_PreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.PreOrden(arbol.inicial);
            System.out.println("PreOrden Generado Correctamente");
            System.out.println("PreOrden Generado Correctamente");
        } catch (IOException ex) {
            Logger.getLogger(frm_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PreOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_Menu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(frm_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InOrden;
    private javax.swing.JButton btn_PosOrden;
    private javax.swing.JButton btn_PreOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
